const Menu=[
    {
        id:1,
        images:"images/s1.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"150$"
    },
    {
        id:2,
        images:"images/s2.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"250$"
    },
    {
        id:3,
        images:"images/s3.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"550$"
    },
    {
        id:4,
        images:"images/s4.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"650$"
    },
    {
        id:5,
        images:"images/s5.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"550$"
    },
    {
        id:6,
        images:"images/s7.jpg",
        category:"Chennai",
        baths:"2/3",
        bed:"2/4",
        price:"1150$"
    },
    {
        id:7,
        images:"images/s8.jpg",
        category:"Bangalore",
        baths:"2/3",
        bed:"2/4",
        price:"1550$"
    },
    {
        id:8,
        images:"images/s9.jpg",
        category:"Bangalore",
        baths:"2/3",
        bed:"2/4",
        price:"1500$"
    },
    {
        id:9,
        images:"images/s10.jpg",
        category:"Bangalore",
        baths:"2/3",
        bed:"2/4",
        price:"1505$"
    },
    {
        id:10,
        images:"images/s11.jpg",
        category:"Andhra",
        baths:"2/3",
        bed:"2/4",
        price:"1507$"
    },
    {
        id:11,
        images:"images/s12.jpg",
        category:"Andhra",
        baths:"2/3",
        bed:"2/4",
        price:"1150$"
    },

]
    
export default Menu;